version: '3.8'
services:
  app:
    build:
      context: ..
      # Path must point to where the file actually is
      dockerfile: .devcontainer/Dockerfile 
    volumes:
      # Use a hardcoded name to prevent "workspace not found" errors
      - ..:/workspaces/auth-service:cached
    network_mode: service:db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=finflow
    ports:
      - '5432:5432'